### ISSUE TITLE
Plugins Admin Settings part of header.

### ISSUE THREAD

**Issue by davarravad** [mudmin/usplugins#2]
I noticed that in US5 that the plugins admin config pages show the configure plugin data within the header of the page.

The Plugin Manager Page looks good..
![image](https://user-images.githubusercontent.com/12216243/63637132-65d15380-c63e-11e9-9e8f-cfa1a340f855.png)

However the plugin settings is part of the header...
![image](https://user-images.githubusercontent.com/12216243/63637141-96b18880-c63e-11e9-9c5c-f8c08a4074ac.png)

**Comment by davarravad** [comment]
![image](https://user-images.githubusercontent.com/12216243/63637163-e98b4000-c63e-11e9-8846-6afaaffd6274.png)

**Comment by Brandin** [comment]
https://userspice.com/bugs/usersc/issue_detail.php?id=679
